"""two new field

Revision ID: b5f7da50829d
Revises: bb22542bb636
Create Date: 2021-04-15 15:18:49.450600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f7da50829d'
down_revision = 'bb22542bb636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_body', table_name='post')
    op.add_column('user', sa.Column('about_me', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.create_index('ix_post_body', 'post', ['body'], unique=False)
    # ### end Alembic commands ###
